name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour - adjust as needed
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate comparison

      - name: Set up upstream remote
        run: |
          git remote add upstream ${{ github.event.repository.parent.clone_url }}
          echo "Upstream remote URL: $(git remote get-url upstream)"

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Get current branch name
        id: branch-name
        run: echo "BRANCH_NAME=$(git branch --show-current)" >> "$GITHUB_OUTPUT"

      - name: Check for differences
        id: diff-check
        run: |
          if ! git diff --quiet ${{ steps.branch-name.outputs.BRANCH_NAME }} upstream/${{ steps.branch-name.outputs.BRANCH_NAME }}; then
            echo "::set-output name=has_diff::true"
          else
            echo "::set-output name=has_diff::false"
          fi

      - name: Merge upstream changes
        if: steps.diff-check.outputs.has_diff == 'true'
        run: |
          echo "Merging upstream changes..."
          git merge upstream/${{ steps.branch-name.outputs.BRANCH_NAME }}
          git push origin ${{ steps.branch-name.outputs.BRANCH_NAME }}
          echo "Fork synced with upstream."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}